travis:
  secure:
    BINSTAR_TOKEN: g4T7tK/+cfMlmHlUMbMtlQ24bHsK04k1Uf199tAjOQTKri0tLwnN4MbXlIm0sYUgKYWJ3i60j7goIG1gXaq04Vh0gklgsMSTTjgayxu5xHC+64iMK0hL1UIvmbSPuilYnz2Cds3eiGxQ6qaRsP5AZ3vbMoye5dZ9HW5IFUoMOy9YVbGztxRLRMX6JckGNanMPdaX+dHV7JnnsK1HWtHCTZcnlzm/RALaswP/mMJ6pD57Ppec3e+kP2JJjc/oUlEPy/hCiGWnSxjG0pdaNwgcBNMaIpRJVSOaq+N8aGQiY0ettlBnGmCpLcVrYFdsqSHp9qj2OivTIHNaxTXIUSS5BvYzvQhCJ4gVjDFwohQ1Ay1EA4S/KHB/za228+wzeuUzqAa8wp6tIE4F+nyOfD+KgwKQ8EfrsHWfQtyy3FK7JwruR/7H3zTex9C6gNjFUf67bRj36ut+rr2+anQ6KLyAf43B/W9HlRPsJd2n0hWZ53Jsh7D4Wal7Nqs0lJWi6wT4hulAIGD4TjBDwoJ4+4gidGCkiSs9Zbt/+SWRE+0W1ndlQ5o3yNsX88g/pUXCH+mr3+Z5WheangJqoyXvv0S1HqrPOu9NtgKrkpcKQtbyWII/+pQjn1JfFkYplJxBUgzMjS7uWy9VcraTahJIOFDWuwJabEUyw5s2hCm5Mn6B/q8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
